[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["build/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200

[context.production.environment]
  DEPLOYMENT_MODE = "serverless"
  MODE = "http"
  ENABLE_CORS = "true"
  SEARCH_MODE = "request"
  REQUIRE_E2E_ENCRYPTION = "true"

[context.deploy-preview.environment]
  DEPLOYMENT_MODE = "serverless"
  MODE = "http"
  ENABLE_CORS = "true"
  SEARCH_MODE = "request"
  REQUIRE_E2E_ENCRYPTION = "true"
